services:
  app:
    container_name: vintage_story_dedicated_server
    image: vintage_story_dedicated_server:latest
    restart: unless-stopped
    build: .
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - 127.0.0.1:42420:42420/tcp #Default Port
    volumes:
      - ./data:/data