name: Push image tag latest to ghcr.io

on:
  push:
    branches: [ "main" ]
    paths:
      - 'dockerfile'
      - 'src/**'
      - 'entrypoint.sh'
      - '.github/workflows/push-image-gh-io.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'dockerfile'
      - 'src/**'
      - 'entrypoint.sh'
      - '.github/workflows/push-image-gh-io.yml'



env:
  PLATAFORM_ARCH: linux/amd64
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ GITHUB.REPOSITORY_OWNER }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATAFORM_ARCH }}
          #driver-opts: image=moby/buildkit:master
                
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfile
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          #proveance: false
          #sbom: false  
          tags: ghcr.io/${{ GITHUB.REPOSITORY }}:latest
